
server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/springtest?serverTimeZone=Asia/Shanghai
    username: springtest
    password: springtest
    driver-class-name: com.mysql.jdbc.Driver


